cmake_minimum_required(VERSION 3.25)
project(Algorithms)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(WIN32)
if(MSVC)
    add_compile_options(/source-charset:utf-8)
else()
    add_compile_options(-fexec-charset=gb2312)
endif()
endif()

set(Base OFF)
set(LeetCode ON)
set(C ON)
set(CPP OFF)

if(Base)
endif()

if(LeetCode)
if(C)
add_executable(0001TwoSumC LeetCode/0001TwoSum/TwoSum.c)
add_executable(0009IsPalindrome LeetCode/0009IsPalindrome/IsPalindrome.c)
add_executable(0013RomanToInt LeetCode/0013RomanToInt/RomanToInt.c)
endif()
if(CPP)
add_executable(0001TwoSumCPP LeetCode/0001TwoSum/TwoSum.cpp)
endif()
endif()